name: Check PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.13.3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir lib
        pip install -r requirements.txt --target=lib/
    - name: Test
      env:
        TWITTER_CONSUMER_KEY: 'dummy'
        TWITTER_CONSUMER_SECRET: 'dummy'
        TWITTER_ACCESS_TOKEN: 'dummy'
        TWITTER_ACCESS_SECRET: 'dummy'
        TWITTER_API_VERSION: '2'
        THREADS_ACCESS_TOKEN: 'dummy'
        BLUESKY_ACCOUNT_HANDLE: 'dummy'
        BLUESKY_ACCOUNT_APP_PASSWORD: 'dummy'
        THREADS_USER_ID: 'dummy'
      run: |
        pip install pytest
        export PYTHONPATH=$PYTHONPATH:$(pwd)/lib
        pytest test/