name: Deploy lambda

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir lib
        pip install -r requirements.txt --target=lib/
    - name: Test
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      run: |
        pip install pytest
        export PYTHONPATH=$PYTHONPATH:$(pwd)/lib
        pytest test/
    - name: Package
      if: success()
      run: |
        zip -ur lys.zip lys.py
        cd lib
        zip -ur ../lys.zip *
        cd ..
    - name: Deploy
      if: success()
      uses: stcalica/update-lambda@0.0.2
      with:
        package: lys.zip
        function-name: LysUpdate
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}